# Generated by Django 3.1.2 on 2020-10-11 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_notebookproduct_smartphone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NotebookProduct',
            new_name='Notebook',
        ),
    ]
