# Generated by Django 3.1.2 on 2020-10-13 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_somemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SomeModel',
        ),
    ]
